# Generated by Django 3.2.16 on 2023-01-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th2928_final', '0002_accountholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountholder',
            old_name='currencies_visited',
            new_name='cities_visited',
        ),
    ]
