# Generated by Django 3.2.16 on 2023-01-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th2928_final', '0004_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abb', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=5)),
            ],
        ),
    ]
