# Generated by Django 3.2.16 on 2023-01-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th2928_final', '0005_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abb',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='state',
            name='postal',
            field=models.CharField(max_length=50),
        ),
    ]
